//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_leads
    {
        public System.Guid lead_guid { get; set; }
        public string lead_id { get; set; }
        public string lead_contact_id { get; set; }
        public string srm_colleague_id { get; set; }
        public string srm_contact_id { get; set; }
        public bool lead_deleted { get; set; }
        public string lead_master_record_id { get; set; }
        public string lead_last_name { get; set; }
        public string lead_first_name { get; set; }
        public string lead_full_name { get; set; }
        public string lead_title { get; set; }
        public string lead_company { get; set; }
        public string lead_street { get; set; }
        public string lead_city { get; set; }
        public string lead_province { get; set; }
        public string lead_postal_code { get; set; }
        public string lead_country { get; set; }
        public string lead_phone { get; set; }
        public string lead_email { get; set; }
        public string lead_description { get; set; }
        public string lead_source { get; set; }
        public string lead_status { get; set; }
        public string lead_owner_id { get; set; }
        public Nullable<int> lead_converted { get; set; }
        public Nullable<System.DateTime> lead_converted_datetime { get; set; }
        public Nullable<bool> lead_unread_by_owner { get; set; }
        public Nullable<System.DateTime> lead_created_datetime { get; set; }
        public string lead_created_by { get; set; }
        public Nullable<System.DateTime> lead_last_modified_datetime { get; set; }
        public string lead_last_modified_by { get; set; }
        public Nullable<System.DateTime> lead_last_activity_datetime { get; set; }
        public Nullable<System.DateTime> lead_last_viewed_datetime { get; set; }
        public Nullable<System.DateTime> lead_last_referenced_datetime { get; set; }
        public string lead_email_bounced_reason { get; set; }
        public Nullable<System.DateTime> lead_email_bounced_datetime { get; set; }
    }
}
