//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_contacts
    {
        public System.Guid contact_guid { get; set; }
        public string contact_id { get; set; }
        public string contact_legacy_id { get; set; }
        public string contact_colleague_id { get; set; }
        public bool contact_deleted { get; set; }
        public string contact_master_record_id { get; set; }
        public string contact_account_id { get; set; }
        public string contact_first_name { get; set; }
        public string contact_middle_name { get; set; }
        public string contact_last_name { get; set; }
        public string contact_full_name { get; set; }
        public string contact_other_street { get; set; }
        public string contact_other_city { get; set; }
        public string contact_other_province { get; set; }
        public string contact_other_postal_code { get; set; }
        public string contact_other_country { get; set; }
        public string contact_mailing_street { get; set; }
        public string contact_mailing_city { get; set; }
        public string contact_mailing_province { get; set; }
        public string contact_mailing_postalcode { get; set; }
        public string contact_mailing_country { get; set; }
        public string contact_business_phone { get; set; }
        public string contact_business_fax { get; set; }
        public string contact_mobile_phone { get; set; }
        public string contact_home_phone { get; set; }
        public string contact_other_phone { get; set; }
        public string contact_asst_phone { get; set; }
        public string contact_reports_to { get; set; }
        public string contact_email { get; set; }
        public string contact_title { get; set; }
        public string contact_department { get; set; }
        public string contact_assistant_name { get; set; }
        public string contact_lead_source { get; set; }
        public Nullable<System.DateTime> contact_birthdate { get; set; }
        public string contact_description { get; set; }
        public string contact_owner_id { get; set; }
        public Nullable<System.DateTime> contact_created_datetime { get; set; }
        public string contact_created_by { get; set; }
        public Nullable<System.DateTime> contact_last_modified_datetime { get; set; }
        public string contact_last_modified_by { get; set; }
        public Nullable<System.DateTime> contact_last_activity_date { get; set; }
        public Nullable<System.DateTime> contact_last_stay_in_touch_request_date { get; set; }
        public Nullable<System.DateTime> contact_last_stay_in_touch_save_date { get; set; }
        public Nullable<System.DateTime> contact_last_viewed_datetime { get; set; }
        public Nullable<System.DateTime> contact_last_referenced_datetime { get; set; }
        public string contact_email_bounced_reason { get; set; }
        public Nullable<System.DateTime> contact_email_bounced_date { get; set; }
        public bool contact_is_email_bounced { get; set; }
        public string contact_primary_academic_program { get; set; }
        public string contact_primary_department { get; set; }
        public string contact_primary_educational_institution { get; set; }
        public string contact_primary_sports_organization { get; set; }
        public string contact_alternate_email { get; set; }
        public string contact_citizenship { get; set; }
        public string contact_country_of_origin { get; set; }
        public string contact_current_address { get; set; }
        public bool contact_deceased { get; set; }
        public bool contact_do_not_contact { get; set; }
        public string contact_ethnicity { get; set; }
        public bool contact_financial_aid_applicant { get; set; }
        public string contact_gender { get; set; }
        public string contact_preferred_phone { get; set; }
        public string contact_preferred_email { get; set; }
        public string contact_primary_address_type { get; set; }
        public string contact_primary_household { get; set; }
        public string contact_primary_business_organization { get; set; }
        public string contact_religion { get; set; }
        public string contact_secondary_address_type { get; set; }
        public string contact_college_email { get; set; }
        public string contact_work_email { get; set; }
        public string contact_work_phone { get; set; }
        public string contact_work_address { get; set; }
        public bool contact_do_not_auto_update { get; set; }
        public string contact_primary_student_organization { get; set; }
        public bool contact_potential_duplicate { get; set; }
        public bool contact_invalid_email_flag { get; set; }
        public string contact_id_card_barcode { get; set; }
        public string contact_type { get; set; }
        public bool contact_international { get; set; }
        public bool contact_stenso19flreg_flag { get; set; }
        public bool contact_mark_delete { get; set; }
        public byte[] contact_barcode { get; set; }
        public Nullable<System.DateTime> contact_barcode_uploaded { get; set; }
        public Nullable<System.DateTime> contact_qrcode_uploaded { get; set; }
        public bool contact_email_opt_out { get; set; }
        public Nullable<System.DateTime> contact_sis_modified_datetime { get; set; }
        public bool contact_alumni_type { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public Nullable<bool> contact_applicant_type { get; set; }
        public Nullable<bool> contact_prospect_type { get; set; }
        public Nullable<bool> contact_student_type { get; set; }
        public Nullable<System.DateTime> contact_id_barcode_uploaded { get; set; }
        public string contact_record_type_id { get; set; }
    }
}
