//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_campaigns
    {
        public System.Guid campaign_guid { get; set; }
        public string campaign_id { get; set; }
        public bool campaign_deleted { get; set; }
        public string campaign_name { get; set; }
        public string campaign_parent_id { get; set; }
        public string campaign_type { get; set; }
        public string campaign_status { get; set; }
        public Nullable<System.DateTime> campaign_start_date { get; set; }
        public Nullable<System.DateTime> campaign_end_date { get; set; }
        public Nullable<double> campaign_num_sent { get; set; }
        public bool campaign_active { get; set; }
        public string campaign_description { get; set; }
        public Nullable<int> campaign_leads_count { get; set; }
        public Nullable<int> campaign_leads_converted { get; set; }
        public Nullable<int> campaign_contacts_count { get; set; }
        public Nullable<int> campaign_responses_count { get; set; }
        public Nullable<int> campaign_opportunities_count { get; set; }
        public string campaign_owner_id { get; set; }
        public Nullable<System.DateTime> campaign_created_datetime { get; set; }
        public string campaign_created_by { get; set; }
        public Nullable<System.DateTime> campaign_modified_datetime { get; set; }
        public string campaign_modifed_by { get; set; }
        public Nullable<System.DateTime> campaign_system_modstamp { get; set; }
        public Nullable<System.DateTime> campaign_last_activity_datetime { get; set; }
        public Nullable<System.DateTime> campaign_last_viewed_datetime { get; set; }
        public Nullable<System.DateTime> campaign_last_referenced_datetime { get; set; }
        public string campaign_record_type_id { get; set; }
        public bool campaign_mark_delete { get; set; }
        public Nullable<bool> campaign_allow_repeat_broadcasts { get; set; }
    }
}
