//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_email_templates
    {
        public System.Guid email_template_guid { get; set; }
        public string email_template_id { get; set; }
        public string email_template_legacy_id { get; set; }
        public string email_template_name { get; set; }
        public string email_template_dev_name { get; set; }
        public string email_template_namespace_prefix { get; set; }
        public string email_template_owner_id { get; set; }
        public string email_template_folder_id { get; set; }
        public string email_template_folder_name { get; set; }
        public string email_template_brand_template_id { get; set; }
        public string email_template_style { get; set; }
        public bool email_template_is_active { get; set; }
        public string email_template_type { get; set; }
        public string email_template_encoding { get; set; }
        public string email_template_description { get; set; }
        public string email_template_subject { get; set; }
        public string email_template_html_value { get; set; }
        public string email_template_body { get; set; }
        public Nullable<int> email_template_times_used { get; set; }
        public Nullable<System.DateTime> email_template_last_used_datetime { get; set; }
        public Nullable<System.DateTime> email_template_created_datetime { get; set; }
        public string email_template_created_by { get; set; }
        public Nullable<System.DateTime> email_template_modified_datetime { get; set; }
        public string email_template_modified_by { get; set; }
        public Nullable<System.DateTime> email_template_system_modstamp { get; set; }
        public Nullable<double> email_template_api_version { get; set; }
        public string email_template_markup { get; set; }
        public bool email_template_deleted { get; set; }
        public bool email_template_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
