//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_form_submissions
    {
        public System.Guid crm_form_guid { get; set; }
        public Nullable<System.Guid> crm_cookie_uuid { get; set; }
        public string crm_form_source { get; set; }
        public string crm_form_firstname { get; set; }
        public string crm_form_lastname { get; set; }
        public string crm_form_emailaddress { get; set; }
        public string crm_form_birthdate { get; set; }
        public Nullable<System.DateTime> crm_form_created_datetime { get; set; }
        public string crm_form_googleclientId { get; set; }
        public Nullable<System.DateTime> crm_form_processed_datetime { get; set; }
        public bool crm_form_process_skip { get; set; }
        public string crm_form_contact_id { get; set; }
        public Nullable<System.DateTime> crm_form_ack_sent { get; set; }
        public string crm_form_mobile_phone { get; set; }
        public string crm_form_city { get; set; }
        public string crm_form_province { get; set; }
        public string crm_form_term { get; set; }
        public string crm_form_program { get; set; }
        public string crm_form_type { get; set; }
        public string crm_form_inquiry_id { get; set; }
        public Nullable<bool> crm_form_indigenous { get; set; }
        public string crm_form_prior_status { get; set; }
        public Nullable<bool> crm_form_sfad_interest { get; set; }
        public Nullable<bool> crm_form_ct_interest { get; set; }
        public Nullable<bool> crm_form_athletics_interest { get; set; }
        public Nullable<bool> crm_form_accessibility_interest { get; set; }
        public Nullable<bool> crm_form_wellness_interest { get; set; }
        public Nullable<bool> crm_form_awards_interest { get; set; }
        public Nullable<bool> crm_form_residence_interest { get; set; }
    }
}
