//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_role_values
    {
        public System.Guid crm_role_value_guid { get; set; }
        public string crm_role_value_id { get; set; }
        public string crm_rv_role_id { get; set; }
        public string crm_rv_name { get; set; }
        public string crm_rv_sender_name { get; set; }
        public string crm_rv_send_emails { get; set; }
        public string crm_rv_default_contact_type { get; set; }
        public string crm_rv_owner_id { get; set; }
        public string crm_rv_modified_by { get; set; }
        public Nullable<System.DateTime> crm_rv_modified_datetime { get; set; }
        public string crm_rv_created_by { get; set; }
        public Nullable<System.DateTime> crm_rv_created_datetime { get; set; }
        public bool crm_rv_deleted_flag { get; set; }
        public bool crm_rv_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
