//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_activities
    {
        public Nullable<System.Guid> activity_guid { get; set; }
        public string activity_id { get; set; }
        public string activity_legacy_id { get; set; }
        public string activity_name_id { get; set; }
        public string activity_legacy_name_id { get; set; }
        public string activity_related_to { get; set; }
        public string activity_legacy_rel_to_id { get; set; }
        public string activity_subject { get; set; }
        public Nullable<System.DateTime> activity_due_date { get; set; }
        public string activity_status { get; set; }
        public string activity_priority { get; set; }
        public bool activity_priority_high { get; set; }
        public string activity_assigned_to { get; set; }
        public string activity_legacy_assigned_to { get; set; }
        public string activity_description { get; set; }
        public bool activity_deleted { get; set; }
        public string activity_school_id { get; set; }
        public string activity_legacy_school { get; set; }
        public bool activity_closed { get; set; }
        public Nullable<System.DateTime> activity_created_date { get; set; }
        public string activity_created_by { get; set; }
        public string activity_mod_date { get; set; }
        public string activity_mod_by { get; set; }
        public Nullable<System.DateTime> activity_sys_timestamp { get; set; }
        public bool activity_archived { get; set; }
        public Nullable<int> activity_call_duration { get; set; }
        public string activity_call_type { get; set; }
        public string activity_call_result { get; set; }
        public string activity_call_obj_id { get; set; }
        public Nullable<System.DateTime> activity_reminder_date { get; set; }
        public bool activity_reminder_set { get; set; }
        public string activity_recurrence_id { get; set; }
        public bool activity_create_recur { get; set; }
        public Nullable<System.DateTime> activity_recurrence_start { get; set; }
        public Nullable<System.DateTime> activity_recurrence_end { get; set; }
        public string activity_recurrence_time_zone { get; set; }
        public string activity_recurrence_type { get; set; }
        public Nullable<int> activity_recurrence_int { get; set; }
        public Nullable<int> activity_recurrence_day_of_week { get; set; }
        public Nullable<int> activity_recurrence_day_of_month { get; set; }
        public string activity_recurrence_instance { get; set; }
        public string activity_recurrence_month_of_year { get; set; }
        public string activity_repeat_task { get; set; }
        public string activity_contactid_cl { get; set; }
        public string activity_oldwhatid_cl { get; set; }
        public string activity_testtype_cl { get; set; }
        public bool activity_cancelled { get; set; }
        public bool activity_copy_events { get; set; }
        public string activity_org_event_id { get; set; }
        public Nullable<double> activity_prospect_score { get; set; }
        public string activity_data_quality_desc { get; set; }
        public Nullable<double> activity_data_quality_score { get; set; }
        public string activity_pri_adv_rec { get; set; }
    }
}
