//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_cookie_history
    {
        public System.Guid crm_cookie_history_uuid { get; set; }
        public Nullable<System.Guid> crm_cookie_uuid { get; set; }
        public string crm_page_visited { get; set; }
        public Nullable<System.DateTime> crm_created_datetime { get; set; }
        public string crm_googleclientId { get; set; }
    }
}
