//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_email_messages
    {
        public System.Guid email_message_guid { get; set; }
        public string email_message_id { get; set; }
        public string email_message_case_id { get; set; }
        public string email_message_activity_id { get; set; }
        public string email_message_contact_id { get; set; }
        public string email_message_account_id { get; set; }
        public string email_message_created_by { get; set; }
        public Nullable<System.DateTime> email_message_created_datetime { get; set; }
        public string email_message_modified_by { get; set; }
        public Nullable<System.DateTime> email_message_modified_datetime { get; set; }
        public Nullable<System.DateTime> email_message_system_mod_stamp { get; set; }
        public string email_message_text_body { get; set; }
        public string email_message_html_body { get; set; }
        public string email_message_headers { get; set; }
        public string email_message_subject { get; set; }
        public string email_message_from_name { get; set; }
        public string email_message_from_address { get; set; }
        public string email_message_to_address { get; set; }
        public string email_message_cc_address { get; set; }
        public string email_message_bcc_address { get; set; }
        public bool email_message_is_incoming { get; set; }
        public bool email_message_has_attachment { get; set; }
        public string email_message_status { get; set; }
        public Nullable<System.DateTime> email_message_datetime { get; set; }
        public bool email_message_deleted { get; set; }
        public string email_message_reply_to_msg_id { get; set; }
        public Nullable<System.Guid> email_message_template_guid { get; set; }
        public Nullable<System.DateTime> email_message_sent_datetime { get; set; }
        public bool email_message_sent { get; set; }
        public string email_message_error { get; set; }
        public string email_message_report_id { get; set; }
        public string email_message_template_id { get; set; }
        public string email_message_secondary_id { get; set; }
        public string email_message_campaign_id { get; set; }
        public string email_message_broadcast_id { get; set; }
        public Nullable<System.Guid> email_message_broadcast_guid { get; set; }
    }
}
