//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_po_course_codes
    {
        public string po_course_code { get; set; }
        public string po_course_created_by { get; set; }
        public Nullable<System.DateTime> po_course_created_datetime { get; set; }
        public string po_course_modifed_by { get; set; }
        public Nullable<System.DateTime> po_course_modified_datetime { get; set; }
    }
}
