//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_settings
    {
        public System.Guid crm_setting_guid { get; set; }
        public string crm_setting_name { get; set; }
        public Nullable<int> crm_setting_number { get; set; }
        public Nullable<int> crm_setting_type { get; set; }
        public string crm_setting_description { get; set; }
        public bool crm_setting_bool { get; set; }
        public string crm_setting_string { get; set; }
        public Nullable<int> crm_setting_int { get; set; }
        public Nullable<System.DateTime> crm_setting_datetime { get; set; }
    }
}
