//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_events
    {
        public System.Guid activity_guid { get; set; }
        public string activity_id { get; set; }
        public string event_name_id { get; set; }
        public string event_related_to_id { get; set; }
        public string event_subject { get; set; }
        public string event_location { get; set; }
        public bool event_all_day { get; set; }
        public Nullable<System.DateTime> event_due_datetime { get; set; }
        public Nullable<System.DateTime> event_due_date_only { get; set; }
        public Nullable<int> event_duration { get; set; }
        public Nullable<System.DateTime> event_start_datetime { get; set; }
        public Nullable<System.DateTime> event_end_datetime { get; set; }
        public string event_description { get; set; }
        public string event_account_id { get; set; }
        public string event_assigned_to_id { get; set; }
        public bool event_private { get; set; }
        public string event_show_time_as { get; set; }
        public bool event_deleted { get; set; }
        public bool event_is_child { get; set; }
        public bool event_is_group_event { get; set; }
        public string event_group_event_type { get; set; }
        public Nullable<System.DateTime> event_created_datetime { get; set; }
        public string event_created_by { get; set; }
        public Nullable<System.DateTime> event_modified_datetime { get; set; }
        public string event_modified_by { get; set; }
        public Nullable<System.DateTime> event_system_modstamp { get; set; }
        public bool event_archived { get; set; }
        public string event_recurrence_activity_id { get; set; }
        public bool event_is_recurring { get; set; }
        public Nullable<System.DateTime> event_recurrence_start { get; set; }
        public Nullable<System.DateTime> event_recurrence_end { get; set; }
        public string event_recurrence_timezone { get; set; }
        public string event_recurrence_type { get; set; }
        public Nullable<int> event_recurrence_interval { get; set; }
        public Nullable<int> event_recurrence_day_of_week_mask { get; set; }
        public Nullable<int> event_recurrence_day_of_month { get; set; }
        public string event_recurrence_instance { get; set; }
        public string event_recurrence_month_of_year { get; set; }
        public Nullable<System.DateTime> event_reminder_datetime { get; set; }
        public bool event_reminder_set { get; set; }
        public string event_department { get; set; }
        public string event_engagement_type { get; set; }
        public string event_activity_extender_id { get; set; }
        public Nullable<System.DateTime> event_start_date { get; set; }
        public Nullable<System.DateTime> event_end_date { get; set; }
        public bool event_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public string event_reminder_dates { get; set; }
        public string event_reminder_email_address { get; set; }
        public Nullable<bool> event_reminder_send_flag { get; set; }
        public Nullable<bool> event_confirmation_send_flag { get; set; }
        public string event_details_field { get; set; }
    }
}
