//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_affiliations
    {
        public System.Guid affiliation_guid { get; set; }
        public string affiliation_id { get; set; }
        public string affiliation_owner_id { get; set; }
        public bool affiliation_deleted { get; set; }
        public string affiliation_key { get; set; }
        public string affiliation_created_by { get; set; }
        public Nullable<System.DateTime> affiliation_system_modstamp { get; set; }
        public string affiliation_last_modified_by { get; set; }
        public Nullable<System.DateTime> affiliation_last_viewed_datetime { get; set; }
        public Nullable<System.DateTime> affiliation_last_referenced_datetime { get; set; }
        public string affiliation_organization_id { get; set; }
        public string lc_student_program_id { get; set; }
        public string affiliation_type { get; set; }
        public string affiliation_description { get; set; }
        public string affiliation_contact_id { get; set; }
        public Nullable<System.DateTime> affiliation_created_datetime { get; set; }
        public Nullable<System.DateTime> affiliation_last_modified_datetime { get; set; }
        public bool affiliation_primary { get; set; }
        public string affiliation_role { get; set; }
        public string affiliation_status { get; set; }
        public Nullable<System.DateTime> affiliation_start_date { get; set; }
        public Nullable<System.DateTime> affiliation_end_date { get; set; }
        public bool affiliation_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public bool affiliation_guid_mismatch { get; set; }
        public Nullable<bool> lc_temp_use_flag { get; set; }
        public string affiliation_program_status { get; set; }
        public Nullable<System.DateTime> affiliation_program_status_date { get; set; }
        public string affiliation_record_type_id { get; set; }
    }
}
