//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_campaign_members
    {
        public System.Guid campaign_member_guid { get; set; }
        public string campaign_member_id { get; set; }
        public bool campaign_member_deleted { get; set; }
        public string campaign_id { get; set; }
        public string campaign_member_lead_id { get; set; }
        public string campaign_member_contact_id { get; set; }
        public string campaign_member_status { get; set; }
        public bool campaign_member_responded { get; set; }
        public Nullable<System.DateTime> campaign_member_created_datetime { get; set; }
        public string campaign_member_created_by { get; set; }
        public Nullable<System.DateTime> campaign_member_modified_datetime { get; set; }
        public string campaign_member_modified_by { get; set; }
        public Nullable<System.DateTime> campaign_member_system_modstamp { get; set; }
        public Nullable<System.DateTime> campaign_member_first_responded_date { get; set; }
    }
}
