//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_scanner_registrations
    {
        public System.Guid crm_scanner_registration_guid { get; set; }
        public string crm_scanner_barcode { get; set; }
        public string crm_scanner_colleague_id { get; set; }
        public string crm_scanner_first_name { get; set; }
        public string crm_scanner_last_name { get; set; }
        public Nullable<System.DateTime> crm_scanner_birth_date { get; set; }
        public string crm_scanner_event_id { get; set; }
        public Nullable<System.DateTime> crm_scanner_registration_processed { get; set; }
        public Nullable<System.DateTime> crm_scanner_modified_date { get; set; }
        public bool crm_scanner_registration_skip { get; set; }
    }
}
