//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_dynamic_content
    {
        public System.Guid crm_dynamic_content_guid { get; set; }
        public string crm_dynamic_content_id { get; set; }
        public string crm_dynamic_content_label { get; set; }
        public string crm_dynamic_content_number { get; set; }
        public string crm_dynamic_content_name { get; set; }
        public bool crm_dynamic_content_available { get; set; }
        public string crm_dynamic_content_html { get; set; }
        public string crm_dynamic_content_text { get; set; }
        public Nullable<System.DateTime> crm_dynamic_content_last_modified_datetime { get; set; }
        public string crm_dynamic_content_recordtype_id { get; set; }
        public Nullable<System.DateTime> crm_dynamic_content_created_datetime { get; set; }
        public bool crm_dynamic_content_mark_delete { get; set; }
        public bool crm_dynamic_content_deleted { get; set; }
        public string crm_dynamic_content_last_modified_by { get; set; }
        public string crm_dynamic_content_created_by { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public string crm_dynamic_content_matching_text { get; set; }
    }
}
