//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_inquiry_programs
    {
        public System.Guid crm_inq_prog_guid { get; set; }
        public string crm_inq_prog_id { get; set; }
        public string crm_inq_prog_number { get; set; }
        public string crm_inq_prog_inquiry_id { get; set; }
        public string crm_inq_prog_program_id { get; set; }
        public string crm_inq_prog_created_by { get; set; }
        public System.DateTime crm_inq_prog_created_datetime { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public bool crm_inq_prog_deleted { get; set; }
        public bool crm_inq_prog_mark_delete { get; set; }
        public string crm_inq_prog_last_modified_by { get; set; }
        public System.DateTime crm_inq_prog_last_modified_datetime { get; set; }
        public Nullable<System.DateTime> crm_inq_prog_ack_sent { get; set; }
    }
}
