//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_reports
    {
        public System.Guid report_guid { get; set; }
        public string crm_report_id { get; set; }
        public string crm_report_name { get; set; }
        public string crm_report_developer_name { get; set; }
        public string crm_report_description { get; set; }
        public string crm_report_folder_name { get; set; }
        public string crm_report_format { get; set; }
        public Nullable<System.DateTime> crm_report_last_run_date { get; set; }
        public bool crm_report_deleted { get; set; }
        public string crm_namespace_prefix { get; set; }
        public string crm_report_owner_id { get; set; }
        public Nullable<System.DateTime> crm_report_system_modstamp { get; set; }
        public Nullable<System.DateTime> crm_report_last_referenced_date { get; set; }
        public Nullable<System.DateTime> crm_report_last_viewed_date { get; set; }
        public string crm_report_modified_by { get; set; }
        public Nullable<System.DateTime> crm_report_modified_date { get; set; }
        public string crm_report_created_by { get; set; }
        public Nullable<System.DateTime> crm_report_created_date { get; set; }
        public bool crm_report_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
