//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_event_registrations
    {
        public System.Guid event_registration_guid { get; set; }
        public string event_registration_id { get; set; }
        public string event_registration_activity_extender_id { get; set; }
        public string event_registration_contact_id { get; set; }
        public Nullable<bool> event_registration_attended { get; set; }
        public Nullable<bool> event_registration_registered { get; set; }
        public Nullable<bool> event_registration_deleted { get; set; }
        public string event_registration_created_by { get; set; }
        public Nullable<System.DateTime> event_registration_created_datetime { get; set; }
        public string event_registration_modified_by { get; set; }
        public Nullable<System.DateTime> event_registration_modified_datetime { get; set; }
        public Nullable<bool> event_registration_checkedin { get; set; }
        public Nullable<bool> event_registration_cancelled { get; set; }
        public bool event_registration_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public Nullable<System.DateTime> event_registration_confirmation_datetime { get; set; }
    }
}
