//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_courses
    {
        public System.Guid course_guid { get; set; }
        public string crm_course_id { get; set; }
        public string course_number { get; set; }
        public string course_name { get; set; }
        public string sis_course_id { get; set; }
        public string course_created_by { get; set; }
        public Nullable<System.DateTime> course_created_datetime { get; set; }
        public string course_modified_by { get; set; }
        public Nullable<System.DateTime> course_modified_datetime { get; set; }
        public Nullable<decimal> course_credit_hours { get; set; }
        public string course_department { get; set; }
        public string course_description { get; set; }
        public string course_desc_extended { get; set; }
        public bool course_deleted { get; set; }
        public bool course_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
