//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_program_enrollments
    {
        public System.Guid crm_program_enrollment_guid { get; set; }
        public string crm_program_enrollment_id { get; set; }
        public string crm_program_enrollment_contact_id { get; set; }
        public string crm_program_enrollment_program_id { get; set; }
        public string crm_program_enrollment_affiliation { get; set; }
        public string crm_program_enrollment_program_plan { get; set; }
        public Nullable<int> crm_program_enrollment_order { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_start_datetime { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_end_datetime { get; set; }
        public bool crm_program_enrollment_eligible_to_enroll { get; set; }
        public string crm_program_enrollment_status { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_submitted_date { get; set; }
        public Nullable<decimal> crm_program_enrollment_gpa { get; set; }
        public string crm_program_enrollment_class_standing { get; set; }
        public Nullable<decimal> crm_program_enrollment_credits_attempted { get; set; }
        public Nullable<decimal> crm_program_enrollment_credits_earned { get; set; }
        public Nullable<decimal> crm_program_enrollment_graduation_year { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_last_referenced_date { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_last_viewed_date { get; set; }
        public string crm_program_enrollment_owner_id { get; set; }
        public string crm_program_enrollment_created_by { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_created_datetime { get; set; }
        public string crm_program_enrollment_modified_by { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_modified_datetime { get; set; }
        public bool crm_program_enrollment_deleted { get; set; }
        public bool crm_program_enrollment_mark_delete { get; set; }
        public bool crm_program_enrollment_guid_mismatch { get; set; }
        public bool crm_program_enrollment_id_mismatch { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public string crm_program_enrollment_key { get; set; }
    }
}
