//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_course_offerings
    {
        public System.Guid course_offering_guid { get; set; }
        public string course_offering_id { get; set; }
        public string sis_course_section_id { get; set; }
        public string course_section_code { get; set; }
        public Nullable<decimal> course_offering_capacity { get; set; }
        public string course_offering_course { get; set; }
        public string course_offering_name { get; set; }
        public Nullable<System.DateTime> course_offering_start_datetime { get; set; }
        public Nullable<System.DateTime> course_offering_end_datetime { get; set; }
        public string course_offering_facility { get; set; }
        public string course_offering_primary_faculty { get; set; }
        public string course_offering_modified_by { get; set; }
        public Nullable<System.DateTime> course_offering_modified_datetime { get; set; }
        public Nullable<System.DateTime> course_offering_created_datetime { get; set; }
        public string course_offering_created_by { get; set; }
        public string course_offering_term { get; set; }
        public string course_offering_time_block { get; set; }
        public bool course_offering_deleted { get; set; }
        public bool course_offering_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
