//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_accounts
    {
        public System.Guid account_guid { get; set; }
        public string account_id { get; set; }
        public bool account_deleted { get; set; }
        public string account_master_record_id { get; set; }
        public string account_name { get; set; }
        public string account_type { get; set; }
        public string account_record_type_id { get; set; }
        public bool lc_account_active { get; set; }
        public string account_parent_account_id { get; set; }
        public string account_billing_address { get; set; }
        public string account_billing_street { get; set; }
        public string account_billing_city { get; set; }
        public string account_billing_province { get; set; }
        public string account_billing_postalcode { get; set; }
        public string account_billing_country { get; set; }
        public string account_shipping_address { get; set; }
        public string account_shipping_street { get; set; }
        public string account_shipping_city { get; set; }
        public string account_shipping_province { get; set; }
        public string account_shipping_postalcode { get; set; }
        public string account_shipping_country { get; set; }
        public string account_phone { get; set; }
        public string account_fax { get; set; }
        public string account_number { get; set; }
        public string account_website { get; set; }
        public string account_industry { get; set; }
        public Nullable<decimal> account_annual_revenue { get; set; }
        public string account_owner_id { get; set; }
        public Nullable<System.DateTime> account_created_date { get; set; }
        public string account_created_by { get; set; }
        public Nullable<System.DateTime> account_modifed_datetime { get; set; }
        public string account_modified_by { get; set; }
        public Nullable<System.DateTime> account_system_modstamp { get; set; }
        public Nullable<System.DateTime> account_last_activity_date { get; set; }
        public Nullable<System.DateTime> account_last_viewed_date { get; set; }
        public Nullable<System.DateTime> account_last_referenced_date { get; set; }
        public string account_source { get; set; }
        public string account_one2one { get; set; }
        public string account_current_address { get; set; }
        public bool account_active { get; set; }
        public string account_department_type { get; set; }
        public string account_colleague_id { get; set; }
        public bool account_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
        public Nullable<bool> account_show_web { get; set; }
        public string account_name_alias { get; set; }
    }
}
