//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_course_connections
    {
        public System.Guid course_connection_guid { get; set; }
        public string course_connection_id { get; set; }
        public string course_connection_name { get; set; }
        public string course_connection_contact_id { get; set; }
        public string course_connection_program_id { get; set; }
        public string course_connection_program_enrollment_id { get; set; }
        public string course_offering_id { get; set; }
        public string course_connection_affiliation_id { get; set; }
        public Nullable<decimal> course_credits_attempted { get; set; }
        public Nullable<decimal> course_credits_earned { get; set; }
        public Nullable<decimal> course_grade { get; set; }
        public bool course_connection_primary { get; set; }
        public string course_connection_record_type { get; set; }
        public string course_connection_status { get; set; }
        public string course_connection_created_by { get; set; }
        public Nullable<System.DateTime> course_connection_created_datetime { get; set; }
        public string course_connection_modified_by { get; set; }
        public Nullable<System.DateTime> course_connection_modified_datetime { get; set; }
        public bool course_connection_deleted { get; set; }
        public Nullable<System.DateTime> contact_last_modified_datetime { get; set; }
        public Nullable<System.DateTime> term_modified_datetime { get; set; }
        public Nullable<System.DateTime> course_offering_modified_datetime { get; set; }
        public Nullable<System.DateTime> sis_stu_course_mod_date { get; set; }
        public bool course_connection_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
