//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_activity_extender
    {
        public System.Guid activity_extender_guid { get; set; }
        public string activity_extender_id { get; set; }
        public Nullable<bool> activity_extender_deleted { get; set; }
        public string activity_extender_created_by { get; set; }
        public Nullable<System.DateTime> activity_extender_created_datetime { get; set; }
        public string activity_extender_modified_by { get; set; }
        public Nullable<System.DateTime> activity_extender_modified_datetime { get; set; }
        public bool activity_extender_mark_delete { get; set; }
        public Nullable<System.DateTime> last_sfsync_datetime { get; set; }
    }
}
