//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class crmdb_entities : DbContext
    {
        public crmdb_entities()
            : base("name=crmdb_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<crm_accounts> crm_accounts { get; set; }
        public virtual DbSet<crm_activities> crm_activities { get; set; }
        public virtual DbSet<crm_activity_extender> crm_activity_extender { get; set; }
        public virtual DbSet<crm_affiliations> crm_affiliations { get; set; }
        public virtual DbSet<crm_applications> crm_applications { get; set; }
        public virtual DbSet<crm_assets> crm_assets { get; set; }
        public virtual DbSet<crm_campaign_members> crm_campaign_members { get; set; }
        public virtual DbSet<crm_campaigns> crm_campaigns { get; set; }
        public virtual DbSet<crm_cases> crm_cases { get; set; }
        public virtual DbSet<crm_contacts> crm_contacts { get; set; }
        public virtual DbSet<crm_course_connections> crm_course_connections { get; set; }
        public virtual DbSet<crm_course_offerings> crm_course_offerings { get; set; }
        public virtual DbSet<crm_courses> crm_courses { get; set; }
        public virtual DbSet<crm_email_broadcasts> crm_email_broadcasts { get; set; }
        public virtual DbSet<crm_email_campaigns> crm_email_campaigns { get; set; }
        public virtual DbSet<crm_email_messages> crm_email_messages { get; set; }
        public virtual DbSet<crm_email_templates> crm_email_templates { get; set; }
        public virtual DbSet<crm_event_registrations> crm_event_registrations { get; set; }
        public virtual DbSet<crm_events> crm_events { get; set; }
        public virtual DbSet<crm_inquiries> crm_inquiries { get; set; }
        public virtual DbSet<crm_leads> crm_leads { get; set; }
        public virtual DbSet<crm_po_course_codes> crm_po_course_codes { get; set; }
        public virtual DbSet<crm_program_enrollments> crm_program_enrollments { get; set; }
        public virtual DbSet<crm_reports> crm_reports { get; set; }
        public virtual DbSet<crm_role_values> crm_role_values { get; set; }
        public virtual DbSet<crm_scanner_registrations> crm_scanner_registrations { get; set; }
        public virtual DbSet<crm_tasks> crm_tasks { get; set; }
        public virtual DbSet<crm_terms> crm_terms { get; set; }
        public virtual DbSet<dynamic_content> dynamic_content { get; set; }
        public virtual DbSet<lcc2_barcodes> lcc2_barcodes { get; set; }
        public virtual DbSet<merge_fields> merge_fields { get; set; }
        public virtual DbSet<soql_queries> soql_queries { get; set; }
        public virtual DbSet<transaction_errors> transaction_errors { get; set; }
        public virtual DbSet<transaction_loads> transaction_loads { get; set; }
        public virtual DbSet<transaction_logs> transaction_logs { get; set; }
        public virtual DbSet<wt_addresses> wt_addresses { get; set; }
        public virtual DbSet<wt_applicants> wt_applicants { get; set; }
        public virtual DbSet<wt_application_statuses> wt_application_statuses { get; set; }
        public virtual DbSet<wt_applications> wt_applications { get; set; }
        public virtual DbSet<wt_core_students> wt_core_students { get; set; }
        public virtual DbSet<wt_course_departments> wt_course_departments { get; set; }
        public virtual DbSet<wt_course_sections> wt_course_sections { get; set; }
        public virtual DbSet<wt_courses> wt_courses { get; set; }
        public virtual DbSet<wt_departments> wt_departments { get; set; }
        public virtual DbSet<wt_divisions> wt_divisions { get; set; }
        public virtual DbSet<wt_institutions> wt_institutions { get; set; }
        public virtual DbSet<wt_off_email_restore> wt_off_email_restore { get; set; }
        public virtual DbSet<wt_program_enrollments> wt_program_enrollments { get; set; }
        public virtual DbSet<wt_programs> wt_programs { get; set; }
        public virtual DbSet<wt_student_course_sections> wt_student_course_sections { get; set; }
        public virtual DbSet<wt_student_courses> wt_student_courses { get; set; }
        public virtual DbSet<wt_student_credentials> wt_student_credentials { get; set; }
        public virtual DbSet<wt_student_programs> wt_student_programs { get; set; }
        public virtual DbSet<wt_student_terms> wt_student_terms { get; set; }
        public virtual DbSet<wt_terms> wt_terms { get; set; }
        public virtual DbSet<sv_core_student_duplicates> sv_core_student_duplicates { get; set; }
        public virtual DbSet<wv_applicants> wv_applicants { get; set; }
        public virtual DbSet<wv_application_statuses> wv_application_statuses { get; set; }
        public virtual DbSet<wv_applications> wv_applications { get; set; }
        public virtual DbSet<wv_colleague_persons> wv_colleague_persons { get; set; }
        public virtual DbSet<wv_core_student_personal> wv_core_student_personal { get; set; }
        public virtual DbSet<wv_core_student_restrictions> wv_core_student_restrictions { get; set; }
        public virtual DbSet<wv_core_student_statuses> wv_core_student_statuses { get; set; }
        public virtual DbSet<wv_core_student_terms> wv_core_student_terms { get; set; }
        public virtual DbSet<wv_course_connections> wv_course_connections { get; set; }
        public virtual DbSet<wv_course_departments> wv_course_departments { get; set; }
        public virtual DbSet<wv_course_sections> wv_course_sections { get; set; }
        public virtual DbSet<wv_courses> wv_courses { get; set; }
        public virtual DbSet<wv_divisions> wv_divisions { get; set; }
        public virtual DbSet<wv_institutions> wv_institutions { get; set; }
        public virtual DbSet<wv_name_history> wv_name_history { get; set; }
        public virtual DbSet<wv_persons> wv_persons { get; set; }
        public virtual DbSet<wv_program_enrollments> wv_program_enrollments { get; set; }
        public virtual DbSet<wv_programs> wv_programs { get; set; }
        public virtual DbSet<wv_schools> wv_schools { get; set; }
        public virtual DbSet<wv_student_applications> wv_student_applications { get; set; }
        public virtual DbSet<wv_student_course_sections> wv_student_course_sections { get; set; }
        public virtual DbSet<wv_student_programs> wv_student_programs { get; set; }
        public virtual DbSet<wv_student_terms> wv_student_terms { get; set; }
        public virtual DbSet<wv_terms> wv_terms { get; set; }
        public virtual DbSet<crm_form_submissions> crm_form_submissions { get; set; }
        public virtual DbSet<crm_dynamic_content> crm_dynamic_content { get; set; }
        public virtual DbSet<crm_cookie_history> crm_cookie_history { get; set; }
        public virtual DbSet<crm_settings> crm_settings { get; set; }
        public virtual DbSet<crm_inquiry_programs> crm_inquiry_programs { get; set; }
    
        public virtual int usp_run_sql_integration_basic(Nullable<bool> full)
        {
            var fullParameter = full.HasValue ?
                new ObjectParameter("full", full) :
                new ObjectParameter("full", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_run_sql_integration_basic", fullParameter);
        }
    }
}
