//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dynamic_content
    {
        public string dynamic_content_id { get; set; }
        public string dynamic_content_label { get; set; }
        public string dynamic_content_name { get; set; }
        public string dynamic_content_matching_id { get; set; }
        public bool dynamic_content_deleted { get; set; }
        public string dynamic_content_owner_id { get; set; }
        public bool dynamic_content_available { get; set; }
        public string dynamic_content_html { get; set; }
        public string dynamic_content_text { get; set; }
        public string dynamic_content_created_by { get; set; }
        public Nullable<System.DateTime> dynamic_content_created_datetime { get; set; }
        public string dynamic_content_modified_by { get; set; }
        public Nullable<System.DateTime> dynamic_content_modified_datetime { get; set; }
        public Nullable<System.DateTime> dynamic_system_modstamp { get; set; }
    }
}
