//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class lcc2_barcodes
    {
        public string sis_student_id { get; set; }
        public string lcc2_barcode_number { get; set; }
        public bool lcc2_barcode_deleted { get; set; }
        public System.DateTime lcc2_barcode_modified_datetime { get; set; }
    }
}
