//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class merge_fields
    {
        public System.Guid merge_field_id { get; set; }
        public System.Guid email_template_id { get; set; }
        public string merge_field { get; set; }
    }
}
