//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class soql_queries
    {
        public System.Guid soql_query_id { get; set; }
        public Nullable<int> soql_query_data_type { get; set; }
        public string soql_query_description { get; set; }
        public string soql_query_string { get; set; }
        public string soql_query_created_by { get; set; }
        public Nullable<System.DateTime> soql_query_created_datetime { get; set; }
        public string soql_query_modified_by { get; set; }
        public Nullable<System.DateTime> soql_query_modified_datetime { get; set; }
    }
}
