//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_logs
    {
        public System.Guid transaction_id { get; set; }
        public string transaction_name { get; set; }
        public Nullable<int> records_inserted { get; set; }
        public Nullable<int> records_updated { get; set; }
        public Nullable<int> records_total { get; set; }
        public Nullable<System.DateTime> last_executed { get; set; }
        public Nullable<double> run_time { get; set; }
        public string transaction_notes { get; set; }
        public Nullable<bool> transaction_successful { get; set; }
    }
}
