//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_errors
    {
        public System.Guid transaction_error_id { get; set; }
        public System.DateTime transaction_error_datetime { get; set; }
        public string transaction_error_message { get; set; }
        public string transaction_type { get; set; }
    }
}
