//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_addresses
    {
        public string sis_address_id { get; set; }
        public string sis_address_lines { get; set; }
        public string sis_address_city { get; set; }
        public string sis_address_state { get; set; }
        public string sis_address_country { get; set; }
        public string sis_address_zip { get; set; }
        public Nullable<System.DateTime> sis_address_created_datetime { get; set; }
        public Nullable<System.DateTime> sis_address_modified_datetime { get; set; }
    }
}
