//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_applicants
    {
        public string sis_applicant_id { get; set; }
        public bool sis_applicant_housing_flag { get; set; }
        public string sis_applicant_comments { get; set; }
        public string sis_applicant_acad_level { get; set; }
        public string sis_applicant_eps_code { get; set; }
        public Nullable<System.DateTime> sis_applicant_created_date { get; set; }
        public Nullable<System.DateTime> sis_applicant_modified_date { get; set; }
    }
}
