//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_course_sections
    {
        public string sis_course_section_id { get; set; }
        public string sis_cs_sec_short_title { get; set; }
        public string sis_cs_sec_sched_type { get; set; }
        public string sis_cs_sec_location { get; set; }
        public Nullable<decimal> sis_cs_sec_min_enroll { get; set; }
        public Nullable<decimal> sis_cs_sec_capacity { get; set; }
        public string sis_cs_sec_subject { get; set; }
        public Nullable<decimal> sis_cs_sec_min_cred { get; set; }
        public string sis_cs_sec_reg_retake_policy { get; set; }
        public bool sis_cs_sec_only_pass_nopass_flag { get; set; }
        public string sis_cs_sec_term { get; set; }
        public string sis_cs_sec_course_no { get; set; }
        public string sis_cs_sec_no { get; set; }
        public Nullable<decimal> sis_cs_sec_billing_cred { get; set; }
        public string sis_cs_sec_course { get; set; }
        public bool sis_cs_sec_petition_reqd_flag { get; set; }
        public string sis_cs_sec_acad_level { get; set; }
        public string sis_cs_sec_cred_type { get; set; }
        public bool sis_cs_sec_allow_pass_flag { get; set; }
        public bool sis_cs_sec_allow_audit_flag { get; set; }
        public string sis_cs_sec_grade_scheme { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_start_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_end_date { get; set; }
        public string sis_cs_sec_comments { get; set; }
        public string sis_cs_sec_topic_code { get; set; }
        public string sis_cs_sec_billing_period_type { get; set; }
        public string sis_cs_sec_gl_no { get; set; }
        public string sis_cs_sec_synonym { get; set; }
        public bool sis_cs_sec_alow_waitlist_flag { get; set; }
        public string sis_cs_sec_billing_method { get; set; }
        public string sis_cs_sec_drop_reg_ref_pol { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_over_reg_start_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_reg_end_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_add_start_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_add_end_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_prereq_end_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_prereg_end_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_drop_end_date { get; set; }
        public string sis_cs_sec_transfer_status { get; set; }
        public string sis_cs_sec_purpose { get; set; }
        public bool sis_cs_sec_faculty_consent_flag { get; set; }
        public string sis_cs_sec_printed_comments { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_drop_gr_reqd_date { get; set; }
        public string sis_cs_sec_name { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_ovr_drop_start_date { get; set; }
        public Nullable<decimal> sis_cs_sec_no_weeks { get; set; }
        public Nullable<decimal> sis_cs_sec_discount_max_amt { get; set; }
        public bool sis_cs_sec_cip_flag { get; set; }
        public bool sis_cs_sec_time_bill_flag { get; set; }
        public string sis_cs_sec_user1 { get; set; }
        public string sis_cs_sec_r2_event { get; set; }
        public bool sis_cs_sec_special_property_flag { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_first_meeting_date { get; set; }
        public Nullable<System.DateTime> sis_cs_sec_last_meeting_date { get; set; }
        public string sis_cs_sec_meeting_info { get; set; }
        public string sis_cs_sec_faculty_info { get; set; }
        public Nullable<System.DateTime> sis_cs_created_date { get; set; }
        public Nullable<System.DateTime> sis_cs_modified_datetime { get; set; }
        public bool sis_cs_sec_override_crs_reqs_flag { get; set; }
    }
}
