//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_course_departments
    {
        public string sis_course_id { get; set; }
        public string sis_course_department { get; set; }
        public Nullable<System.DateTime> sis_course_department_modified_datetime { get; set; }
        public Nullable<System.DateTime> sis_course_department_created_datetime { get; set; }
        public bool sis_course_department_deleted { get; set; }
    }
}
