//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_core_students
    {
        public string sis_student_id { get; set; }
        public string sis_stu_first_name { get; set; }
        public string sis_stu_last_name { get; set; }
        public string sis_stu_middle_name { get; set; }
        public string sis_stu_hist_last_name { get; set; }
        public Nullable<System.DateTime> sis_stu_birth_date { get; set; }
        public string sis_stu_gender { get; set; }
        public string sis_stu_pref_email { get; set; }
        public string sis_stu_off_email { get; set; }
        public string sis_stu_address { get; set; }
        public string sis_stu_city { get; set; }
        public string sis_stu_state { get; set; }
        public string sis_stu_country { get; set; }
        public string sis_stu_zip { get; set; }
        public string sis_stu_home_phone { get; set; }
        public string sis_stu_per_phone { get; set; }
        public string sis_stu_marital_status { get; set; }
        public string sis_stu_native_lang { get; set; }
        public string sis_stu_alien_status { get; set; }
        public bool sis_stu_international_flag { get; set; }
        public string sis_stu_program { get; set; }
        public Nullable<int> sis_stu_prog_start_year { get; set; }
        public string sis_stu_prog_start_term { get; set; }
        public string sis_stu_location { get; set; }
        public bool sis_stu_restriction_flag { get; set; }
        public bool sis_stu_duplicate_flag { get; set; }
        public bool sis_stu_privacy_flag { get; set; }
        public bool sis_stu_deleted_flag { get; set; }
        public string sis_stu_aboriginal { get; set; }
        public string sis_stu_app_status { get; set; }
        public string crm_student_stage { get; set; }
        public bool sis_stu_alumni_type { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public bool sis_stu_mark_delete { get; set; }
        public bool sis_stu_student_type { get; set; }
        public bool sis_stu_applicant_type { get; set; }
    }
}
