//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_departments
    {
        public string sis_department_id { get; set; }
        public Nullable<System.DateTime> sis_department_modified_datetime { get; set; }
        public Nullable<System.DateTime> sis_department_created_datetime { get; set; }
        public string sis_department_desc { get; set; }
        public string sis_department_division_code { get; set; }
        public string sis_department_active_code { get; set; }
        public string sis_department_created_by { get; set; }
        public string sis_department_modified_by { get; set; }
        public string sis_department_head_id { get; set; }
        public string sis_department_type { get; set; }
        public bool sis_department_deleted { get; set; }
        public bool sis_department_mark_delete { get; set; }
    }
}
