//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_institutions
    {
        public string sis_institution_id { get; set; }
        public string crm_account_id { get; set; }
        public string sis_inst_type { get; set; }
        public string sis_inst_name { get; set; }
        public string sis_inst_address { get; set; }
        public string sis_inst_city { get; set; }
        public string sis_inst_state { get; set; }
        public string sis_inst_zip { get; set; }
        public string sis_inst_phone { get; set; }
        public bool sis_inst_deleted { get; set; }
        public Nullable<System.DateTime> sis_inst_mod_date { get; set; }
        public Nullable<bool> update { get; set; }
    }
}
