//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_program_enrollments
    {
        public string crm_program_enrollment_student_id { get; set; }
        public string crm_program_enrollment_program_id { get; set; }
        public System.DateTime crm_program_enrollment_start_date { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_end_date { get; set; }
        public string crm_program_enrollment_admit_status { get; set; }
        public string crm_program_enrollment_location { get; set; }
        public string crm_program_enrollment_catalog { get; set; }
        public string crm_program_enrollment_department { get; set; }
        public string crm_program_enrollment_division { get; set; }
        public string crm_program_enrollment_school { get; set; }
        public string crm_program_enrollment_comments { get; set; }
        public string crm_program_enrollment_eval_include_code { get; set; }
        public string crm_program_enrollment_printed_comments { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_eval_date { get; set; }
        public string crm_program_enrollment_eval_status { get; set; }
        public Nullable<decimal> crm_program_enrollment_combined_cred { get; set; }
        public Nullable<decimal> crm_program_enrollment_combined_gpa { get; set; }
        public Nullable<decimal> crm_program_enrollment_inst_cred { get; set; }
        public Nullable<decimal> crm_program_enrollment_inst_gpa { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_acad_cred_end_date { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_ant_cmpl_date { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_created_date { get; set; }
        public Nullable<System.DateTime> crm_program_enrollment_modified_date { get; set; }
        public Nullable<short> crm_program_enrollment_order { get; set; }
        public bool crm_program_enrollment_mark_delete { get; set; }
    }
}
