//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_programs
    {
        public string sis_program_id { get; set; }
        public string sis_program_desc { get; set; }
        public string sis_program_title { get; set; }
        public string sis_program_acad_level { get; set; }
        public Nullable<bool> sis_program_active_flag { get; set; }
        public bool sis_program_stu_select_flag { get; set; }
        public Nullable<System.DateTime> sis_program_start_date { get; set; }
        public Nullable<System.DateTime> sis_program_end_date { get; set; }
        public string sis_program_comments { get; set; }
        public string sis_program_created_by { get; set; }
        public Nullable<System.DateTime> sis_program_created_date { get; set; }
        public string sis_program_modified_by { get; set; }
        public bool sis_program_allow_grad_flag { get; set; }
        public string sis_program_grade_scheme { get; set; }
        public string sis_program_transcript_grouping { get; set; }
        public bool sis_program_create_application_flag { get; set; }
        public Nullable<decimal> sis_program_admit_capacity { get; set; }
        public string sis_program_catalogs { get; set; }
        public string sis_program_ccds { get; set; }
        public string sis_program_locations { get; set; }
        public string sis_program_departments { get; set; }
        public string sis_program_gov_codes { get; set; }
        public Nullable<System.DateTime> sis_program_modified_datetime { get; set; }
        public bool sis_program_deleted { get; set; }
        public bool sis_program_active { get; set; }
        public bool sis_program_mark_delete { get; set; }
    }
}
