//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_student_terms
    {
        public string sis_sttr_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_term_id { get; set; }
        public string sis_sttr_type { get; set; }
        public Nullable<System.DateTime> sis_term_modified_date { get; set; }
        public bool sis_stu_term_deleted { get; set; }
        public bool sis_stu_term_mark_delete { get; set; }
    }
}
