//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_student_course_sections
    {
        public string sis_scs_id { get; set; }
        public string sis_cs_id { get; set; }
        public string sis_stc_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_scs_reg_method { get; set; }
        public string sis_scs_location { get; set; }
        public bool sis_scs_ar_posted_flag { get; set; }
        public string sis_scs_reg_time_period { get; set; }
        public Nullable<System.DateTime> sis_scs_created_date { get; set; }
        public Nullable<System.DateTime> sis_scs_modified_date { get; set; }
        public bool sis_scs_mark_delete { get; set; }
    }
}
