//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_student_courses
    {
        public string sis_stu_course_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_stu_course_term { get; set; }
        public string sis_stu_course_name { get; set; }
        public string sis_stu_course_title { get; set; }
        public string sis_stu_course_subject { get; set; }
        public string sis_stu_course_number { get; set; }
        public string sis_stu_course_section { get; set; }
        public string sis_stu_course_campus { get; set; }
        public Nullable<System.DateTime> sis_stu_course_mod_date { get; set; }
        public bool sis_stu_course_deleted { get; set; }
        public Nullable<bool> sis_stu_course_mark_delete { get; set; }
    }
}
