//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_student_credentials
    {
        public string sis_student_id { get; set; }
        public string crm_program_id { get; set; }
        public Nullable<System.DateTime> sis_student_cred_date { get; set; }
        public string sis_student_cred_type { get; set; }
        public Nullable<System.DateTime> sis_student_cred_created_datetime { get; set; }
        public Nullable<System.DateTime> sis_student_cred_modified_datetime { get; set; }
        public bool sis_student_cred_deleted { get; set; }
        public bool sis_student_cred_mark_delete { get; set; }
    }
}
