//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wt_terms
    {
        public string sis_term_id { get; set; }
        public string sis_term_name { get; set; }
        public string sis_term_desc { get; set; }
        public string sis_reporting_year { get; set; }
        public string sis_term_year { get; set; }
        public Nullable<System.DateTime> sis_term_prereg_start_date { get; set; }
        public Nullable<System.DateTime> sis_term_prereg_end_date { get; set; }
        public Nullable<System.DateTime> sis_term_reg_start_date { get; set; }
        public Nullable<System.DateTime> sis_term_start_date { get; set; }
        public Nullable<System.DateTime> sis_term_reg_end_date { get; set; }
        public Nullable<System.DateTime> sis_term_end_date { get; set; }
        public string sis_term_reporting_term { get; set; }
        public Nullable<System.DateTime> sis_term_add_start_date { get; set; }
        public Nullable<System.DateTime> sis_term_add_end_date { get; set; }
        public Nullable<System.DateTime> sis_term_drop_grad_reqd_date { get; set; }
        public Nullable<System.DateTime> sis_term_drop_start_date { get; set; }
        public Nullable<System.DateTime> sis_term_drop_end_date { get; set; }
        public Nullable<short> sis_term_sequence_no { get; set; }
        public string sis_term_created_by { get; set; }
        public Nullable<System.DateTime> sis_term_created_date { get; set; }
        public string sis_term_modified_by { get; set; }
        public Nullable<System.DateTime> sis_term_modified_date { get; set; }
        public Nullable<System.DateTime> sis_term_bill_end_date { get; set; }
        public bool sis_term_use_in_best_fit_calc { get; set; }
        public Nullable<System.DateTime> sis_term_census_dates { get; set; }
        public bool sis_term_deleted { get; set; }
        public bool sis_term_mark_delete { get; set; }
    }
}
