//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_applicants
    {
        public string sis_application_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_app_program { get; set; }
        public string sis_app_location { get; set; }
        public string sis_app_start_term { get; set; }
        public string sis_app_start_year { get; set; }
        public string sis_app_start_session { get; set; }
        public string sis_app_stu_load_intent { get; set; }
        public string sis_app_admit_status { get; set; }
        public string sis_app_status { get; set; }
        public Nullable<System.DateTime> sis_app_status_date { get; set; }
        public string sis_app_stage { get; set; }
        public Nullable<System.DateTime> sis_app_offer_due_date { get; set; }
        public string sis_app_parent_edu_level { get; set; }
        public Nullable<System.DateTime> sis_app_mod_date { get; set; }
    }
}
