//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_applications
    {
        public string sis_application_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_appl_program { get; set; }
        public string sis_appl_location { get; set; }
        public string sis_appl_start_term { get; set; }
        public string sis_appl_start_year { get; set; }
        public string sis_appl_start_session { get; set; }
        public string sis_appl_stu_load_intent { get; set; }
        public int sis_appl_fa_intent_flag { get; set; }
        public int sis_appl_active_stu_program_flag { get; set; }
        public string sis_appl_admit_status { get; set; }
        public string sis_appl_status { get; set; }
        public Nullable<System.DateTime> sis_appl_status_date { get; set; }
        public string sis_appl_stage { get; set; }
        public Nullable<System.DateTime> sis_appl_offer_due_date { get; set; }
        public string sis_appl_parent_edu_level { get; set; }
        public Nullable<System.DateTime> sis_appl_modified_date { get; set; }
        public Nullable<System.DateTime> sis_appl_date { get; set; }
    }
}
