//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_application_statuses
    {
        public string sis_application_id { get; set; }
        public string sis_appl_status { get; set; }
        public Nullable<System.DateTime> sis_appl_status_datetime { get; set; }
    }
}
