//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_colleague_persons
    {
        public string ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string PREFERRED_NAME { get; set; }
        public Nullable<System.DateTime> PERSON_CHANGE_DATE { get; set; }
        public Nullable<System.DateTime> PERSON_ADD_DATE { get; set; }
        public string BIRTH_NAME_LAST { get; set; }
        public string BIRTH_NAME_FIRST { get; set; }
        public string BIRTH_NAME_MIDDLE { get; set; }
        public string PERSON_CORP_INDICATOR { get; set; }
        public string PRIVACY_FLAG { get; set; }
        public string PERSONAL_PRONOUN { get; set; }
        public string PERSON_CHOSEN_FIRST_NAME { get; set; }
        public string PERSON_CHOSEN_LAST_NAME { get; set; }
        public string PERSON_CHOSEN_MIDDLE_NAME { get; set; }
    }
}
