//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_courses
    {
        public string sis_course_id { get; set; }
        public string sis_course_title { get; set; }
        public string sis_course_cred_type { get; set; }
        public string sis_course_name { get; set; }
        public string sis_course_desc { get; set; }
        public string sis_course_short_title { get; set; }
        public string sis_course_subject { get; set; }
        public Nullable<decimal> sis_course_min_cred { get; set; }
        public Nullable<decimal> sis_course_max_cred { get; set; }
        public string sis_course_prereqs { get; set; }
        public string sis_course_no { get; set; }
        public string sis_course_cip { get; set; }
        public string sis_course_retake_policy { get; set; }
        public Nullable<System.DateTime> sis_course_start_date { get; set; }
        public Nullable<System.DateTime> sis_course_end_date { get; set; }
        public string sis_course_acad_level { get; set; }
        public string sis_course_grade_scheme { get; set; }
        public string sis_course_sched_type { get; set; }
        public string sis_course_billing_period_type { get; set; }
        public string sis_course_drop_reg_ref_pol { get; set; }
        public string sis_course_billing_method { get; set; }
        public string sis_course_comments { get; set; }
        public Nullable<decimal> sis_course_billing_cred { get; set; }
        public Nullable<decimal> sis_course_no_weeks { get; set; }
        public string sis_course_transfer_status { get; set; }
        public int sis_course_count_retake_cred_flag { get; set; }
        public int sis_course_allow_audit_flag { get; set; }
        public int sis_course_allow_waitlist_flag { get; set; }
        public string sis_course_topic_code { get; set; }
        public Nullable<decimal> sis_course_capacity { get; set; }
        public Nullable<decimal> sis_course_min_enrol { get; set; }
        public string sis_course_subject_idx { get; set; }
        public int sis_waitlist_mult_sect_flag { get; set; }
        public Nullable<System.DateTime> sis_course_prtl_cc_update_datetime { get; set; }
        public Nullable<System.DateTime> sis_course_created_date { get; set; }
        public Nullable<System.DateTime> sis_course_modified_datetime { get; set; }
    }
}
