//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_core_student_personal
    {
        public string sis_student_id { get; set; }
        public string sis_stu_first_name { get; set; }
        public string sis_stu_last_name { get; set; }
        public string sis_stu_middle_name { get; set; }
        public string sis_stu_hist_last_name { get; set; }
        public Nullable<System.DateTime> sis_stu_birth_date { get; set; }
        public string sis_stu_gender { get; set; }
        public string sis_stu_pref_email { get; set; }
        public string sis_stu_marital_status { get; set; }
        public string sis_stu_native_lang { get; set; }
        public string sis_stu_alien_status { get; set; }
        public int sis_stu_international_flag { get; set; }
        public int sis_stu_duplicate_flag { get; set; }
        public int sis_stu_privacy_flag { get; set; }
        public string sis_stu_aboriginal { get; set; }
        public Nullable<System.DateTime> sis_stu_mod_date { get; set; }
        public Nullable<System.DateTime> sis_stu_mod_time { get; set; }
        public Nullable<System.DateTime> sis_stu_add_date { get; set; }
        public Nullable<System.DateTime> sis_stu_add_time { get; set; }
    }
}
