//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_core_student_restrictions
    {
        public string sis_student_id { get; set; }
        public Nullable<System.DateTime> sis_stu_restrict_mod_date { get; set; }
    }
}
