//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_core_student_statuses
    {
        public string sis_student_id { get; set; }
        public string sis_stu_stage { get; set; }
        public string sis_app_status { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
