//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_divisions
    {
        public string sis_division_id { get; set; }
        public string sis_division_desc { get; set; }
        public string sis_division_head { get; set; }
        public string sis_division_school { get; set; }
        public Nullable<System.DateTime> sis_division_created_date { get; set; }
        public string sis_division_created_by { get; set; }
        public string sis_division_modified_by { get; set; }
        public string sis_division_type { get; set; }
        public string sis_division_department_code { get; set; }
        public string sis_division_location { get; set; }
        public Nullable<System.DateTime> sis_division_modified_datetime { get; set; }
    }
}
