//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_name_history
    {
        public string sis_student_id { get; set; }
        public string sis_former_last_name { get; set; }
        public string sis_former_first_name { get; set; }
        public string sis_former_middle_name { get; set; }
    }
}
