//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_persons
    {
        public string sis_person_id { get; set; }
        public string sis_person_last_name { get; set; }
        public string sis_person_source { get; set; }
        public string sis_person_first_name { get; set; }
        public string sis_person_middle_name { get; set; }
        public string sis_person_prefix { get; set; }
        public string sis_person_preferred_address { get; set; }
        public string sis_joint_person { get; set; }
        public string sis_person_ssn { get; set; }
        public string sis_person_status { get; set; }
        public string sis_person_gender { get; set; }
        public string sis_person_marital_status { get; set; }
        public Nullable<System.DateTime> sis_person_birth_date { get; set; }
        public string sis_person_preferred_name { get; set; }
        public string sis_person_ethnic { get; set; }
        public string sis_person_native_language { get; set; }
        public string sis_person_birth_name_last { get; set; }
        public string sis_person_birth_name_first { get; set; }
        public string sis_person_birth_name_middle { get; set; }
        public string sis_person_pref_residence { get; set; }
        public string sis_person_bus_address { get; set; }
        public Nullable<System.DateTime> sis_person_country_entry_date { get; set; }
        public int sis_person_corp_flag { get; set; }
        public string sis_person_residence_country { get; set; }
        public Nullable<System.DateTime> sis_person_origin_date { get; set; }
        public string sis_person_origin_code { get; set; }
        public string sis_person_visa_type { get; set; }
        public string sis_person_citizenship { get; set; }
        public string sis_emer_contact_name { get; set; }
        public string sis_emer_contact_phone { get; set; }
        public int sis_person_directory_flag { get; set; }
        public int sis_person_privacy_flag { get; set; }
        public string sis_person_primary_language { get; set; }
        public string sis_person_gender_identity { get; set; }
        public string sis_person_pronoun { get; set; }
        public string sis_person_chosen_first_name { get; set; }
        public string sis_person_chosen_last_name { get; set; }
        public string sis_person_chosen_middle_name { get; set; }
        public string sis_person_jati_id { get; set; }
        public string sis_person_sexual_orientation { get; set; }
        public Nullable<System.DateTime> sis_person_created_datetime { get; set; }
        public Nullable<System.DateTime> sis_person_modified_datetime { get; set; }
    }
}
