//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_program_enrollments
    {
        public string sis_student_id { get; set; }
        public string sis_student_program { get; set; }
        public Nullable<System.DateTime> sis_student_program_start_date { get; set; }
        public Nullable<System.DateTime> sis_student_program_end_date { get; set; }
        public string sis_student_program_admit_status { get; set; }
        public string sis_student_program_location { get; set; }
        public string sis_student_program_catalog { get; set; }
        public string sis_student_program_department { get; set; }
        public string sis_student_program_division { get; set; }
        public string sis_student_program_school { get; set; }
        public string sis_student_program_comments { get; set; }
        public string sis_student_program_eval_include_code { get; set; }
        public string sis_student_program_printed_comments { get; set; }
        public Nullable<System.DateTime> sis_student_program_eval_date { get; set; }
        public string sis_student_program_eval_status { get; set; }
        public Nullable<decimal> sis_student_program_combined_cred { get; set; }
        public Nullable<decimal> sis_student_program_combined_gpa { get; set; }
        public Nullable<decimal> sis_student_program_inst_cred { get; set; }
        public Nullable<decimal> sis_student_program_inst_gpa { get; set; }
        public Nullable<System.DateTime> sis_student_program_acad_cred_end_date { get; set; }
        public Nullable<System.DateTime> sis_student_program_ant_cmpl_date { get; set; }
        public Nullable<System.DateTime> sis_student_program_created_date { get; set; }
        public Nullable<System.DateTime> sis_student_program_modified_date { get; set; }
        public Nullable<long> unique { get; set; }
        public Nullable<long> sis_student_program_order { get; set; }
    }
}
