//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_schools
    {
        public string sis_school_id { get; set; }
        public string sis_school_desc { get; set; }
        public string sis_school_head_id { get; set; }
        public string sis_school_created_by { get; set; }
        public Nullable<System.DateTime> sis_school_created_date { get; set; }
        public string sis_school_modified_by { get; set; }
        public Nullable<System.DateTime> sis_school_modified_date { get; set; }
        public string sis_school_location_code { get; set; }
        public string sis_division_code { get; set; }
    }
}
