//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_student_applications
    {
        public string sis_application_id { get; set; }
        public string crm_contact_id { get; set; }
        public string sis_student_id { get; set; }
        public string crm_program_id { get; set; }
        public string sis_appl_location { get; set; }
        public Nullable<int> sis_appl_start_year { get; set; }
        public string sis_appl_start_term { get; set; }
        public string sis_appl_stu_load_intent { get; set; }
        public Nullable<System.DateTime> sis_appl_offer_due_date { get; set; }
        public Nullable<System.DateTime> sis_alt_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_app_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_con_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_dtc_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_dac_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_fi_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_fw_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_ms_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_ntq_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_ofi_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_ofc_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_pas_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_par_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_ppr_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_w_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_pr_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_sc_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_unc_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_wtl_status_datetime { get; set; }
        public Nullable<System.DateTime> sis_wap_status_datetime { get; set; }
        public string sis_appl_parent_edu_level { get; set; }
        public string sis_appl_admit_status { get; set; }
        public string sis_appl_status { get; set; }
        public Nullable<System.DateTime> sis_appl_status_date { get; set; }
        public string sis_appl_stage { get; set; }
        public bool sis_appl_mark_delete { get; set; }
        public Nullable<System.DateTime> sis_appl_date { get; set; }
        public Nullable<System.DateTime> sis_appl_modified_date { get; set; }
        public Nullable<long> RN { get; set; }
    }
}
