//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lc.crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_student_programs
    {
        public string sis_stu_program_id { get; set; }
        public string sis_student_id { get; set; }
        public string sis_stu_program_code { get; set; }
        public string sis_stu_program_location { get; set; }
        public string sis_stu_program_admit_status { get; set; }
        public Nullable<System.DateTime> sis_stu_program_created_date { get; set; }
        public Nullable<System.DateTime> sis_stu_program_modified_date { get; set; }
        public string sis_stu_program_status { get; set; }
        public Nullable<System.DateTime> sis_stu_program_status_date { get; set; }
        public Nullable<System.DateTime> sis_stu_program_start_date { get; set; }
        public Nullable<System.DateTime> sis_stu_program_end_date { get; set; }
        public Nullable<long> RowNum { get; set; }
    }
}
